#! /bin/bash

echo "===================="
echo "LINUX SYSTEM MONITOR"
echo "===================="

echo " "
echo "==== System Information ===="

echo "Host Name    : $(hostname)"
echo "Current User : $(whoami)"
echo "Date & Time  : $(date)"
echo "Uptime       : $(uptime -p)"
echo "Kernel       : $(uname -r)"
echo "OS           : $(grep '^PRETTY_NAME=' /etc/os-release | cut -d= -f2 | tr -d '"')"

echo " "
echo "====MEMORY USAGE===="
free -h

echo " "
echo "====DISK USAGE===="
df -h

echo " "
echo "====CPU USAGE===="
echo "CPU Cores  : $(nproc)"
echo "LOAD AVERAGE : $(uptime | awk -F 'load average:' ' {print $2}')"

echo " "
echo "====TOP CPU PROCESSES===="
ps aux --sort=-%cpu | head -6

echo " "
echo "=== TOP MEMORY PROCESSES===="
ps aux --sort=-%mem | head -6

echo " "
echo "========================"
echo "MONITORING COMPLETED"
echo "========================"
